// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kolmahpstqwrqrcljtsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbG1haHBzdHF3cnFyY2xqdHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzE2NTAsImV4cCI6MjA3MjYwNzY1MH0.BMxEGL_Xnwkige9-I2gq2pSs5LbjjR_GGa5Of0BHDVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});